# Generated by Django 4.2.6 on 2023-10-22 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 13 digits only!', regex='^\\d{10}')]),
        ),
    ]
