# Generated by Django 4.2.6 on 2024-07-09 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('accounts', '0002_alter_user_business_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_id',
            field=models.ForeignKey(default='2febc077-ddfb-416f-914d-9edbfee45e9b', on_delete=django.db.models.deletion.CASCADE, related_name='user_business', to='business.business'),
            preserve_default=False,
        ),
    ]
