# Generated by Django 4.2.6 on 2024-01-16 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('accounts', '0002_remove_user_business_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_id',
            field=models.ForeignKey(default='b830cf37-361f-40b8-81c7-0c6f005ee33c', on_delete=django.db.models.deletion.CASCADE, related_name='user_business', to='business.business'),
            preserve_default=False,
        ),
    ]
