# Generated by Django 4.2.6 on 2023-11-07 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_remove_campaign_actions_alter_lead_status'),
        ('accounts', '0002_remove_user_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_id',
            field=models.ForeignKey(default="922b2a88-2def-4fff-b947-f4602b2642a7",
                                    on_delete=django.db.models.deletion.CASCADE, related_name='user_business', to='business.business'),
            preserve_default=False,
        ),
    ]
