# Generated by Django 4.2.6 on 2023-11-15 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_business_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business_id',
        ),
    ]
