# Generated by Django 4.2.6 on 2023-11-16 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_rename_type_campaign_type_of'),
        ('accounts', '0004_remove_user_business_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_id',
            field=models.ForeignKey(default="bd048f75-0e40-46d4-aed2-04fbae92afab",
                                    on_delete=django.db.models.deletion.CASCADE, related_name='user_business', to='business.business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
