# Generated by Django 4.2.6 on 2024-01-16 13:45

import cloudinary_storage.storage
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('avatar', models.ImageField(blank=True, null=True,
                 storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='user_avatar/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk_id', models.CharField(max_length=255)),
                ('message_id', models.CharField(max_length=255)),
                ('from_number', models.CharField(max_length=15)),
                ('to_number', models.CharField(max_length=15)),
                ('sent_at', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('answer_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('charged_duration', models.IntegerField(blank=True, null=True)),
                ('file_duration', models.FloatField(blank=True, null=True)),
                ('dtmf_codes', models.CharField(max_length=255)),
                ('scenario_id', models.CharField(
                    max_length=255, blank=True, null=True)),
                ('scenario_name', models.CharField(
                    max_length=255, blank=True, null=True)),
                ('collected_dtmfs', models.TextField(blank=True, null=True)),
                ('spoken_input', models.TextField(blank=True, null=True)),
                ('price_per_second', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(max_length=3, blank=True, null=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('group_name', models.CharField(
                    max_length=255, blank=True, null=True)),
                ('status_id', models.IntegerField(blank=True, null=True)),
                ('status_name', models.CharField(
                    max_length=255, blank=True, null=True)),
                ('status_description', models.TextField(blank=True, null=True)),
                ('error_group_id', models.IntegerField(blank=True, null=True)),
                ('error_group_name', models.CharField(
                    max_length=255, blank=True, null=True)),
                ('error_id', models.IntegerField(blank=True, null=True)),
                ('error_name', models.CharField(
                    max_length=255, blank=True, null=True)),
                ('error_description', models.TextField(blank=True, null=True)),
                ('error_permanent', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.CharField(editable=False, max_length=4,
                 primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('leads', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type_of', models.CharField(choices=[
                 ('UPLOAD', 'Upload'), ('DIRECT', 'Direct')], max_length=30)),
                ('converted', models.IntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='business_campaign', to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.CharField(editable=False, max_length=4,
                 primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(
                    blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONVERTED', 'Converted'), (
                    'REJECTED', 'Rejected')], default='Pending', max_length=20)),
                ('actions', models.CharField(max_length=255)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='campaign_lead', to='business.campaign')),
            ],
        ),
    ]
