# Generated by Django 4.2.6 on 2023-11-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='actions',
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONVERTED', 'Converted'), ('REJECTED', 'Rejected')], max_length=20),
        ),
    ]
