# Generated by Django 4.2.6 on 2024-01-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callreport',
            name='charged_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callreport',
            name='dtmf_codes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='callreport',
            name='error_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callreport',
            name='error_group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callreport',
            name='error_group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='callreport',
            name='error_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callreport',
            name='error_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='callreport',
            name='error_permanent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callreport',
            name='file_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callreport',
            name='group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callreport',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='callreport',
            name='spoken_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callreport',
            name='status_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callreport',
            name='status_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callreport',
            name='status_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
