# Generated by Django 4.2.6 on 2024-01-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_callreport_collected_dtmfs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callreport',
            old_name='dtmf_codes',
            new_name='bulkId',
        ),
        migrations.RenameField(
            model_name='callreport',
            old_name='charged_duration',
            new_name='chargedDuration',
        ),
        migrations.RenameField(
            model_name='callreport',
            old_name='collected_dtmfs',
            new_name='collectedDtmfs',
        ),
        migrations.RenameField(
            model_name='callreport',
            old_name='error_group_name',
            new_name='dtmfCodes',
        ),
        migrations.RenameField(
            model_name='callreport',
            old_name='error_description',
            new_name='errorDescription',
        ),
        migrations.RenameField(
            model_name='callreport',
            old_name='error_group_id',
            new_name='errorGroupId',
        ),
        migrations.RenameField(
            model_name='callreport',
            old_name='error_name',
            new_name='errorGroupName',
        ),
        migrations.RenameField(
            model_name='callreport',
            old_name='error_id',
            new_name='errorId',
        ),
        migrations.RenameField(
            model_name='callreport',
            old_name='group_name',
            new_name='errorName',
        ),
        migrations.RenameField(
            model_name='callreport',
            old_name='error_permanent',
            new_name='errorPermanent',
        ),
        migrations.RenameField(
            model_name='callreport',
            old_name='file_duration',
            new_name='fileDuration',
        ),
        migrations.RenameField(
            model_name='callreport',
            old_name='group_id',
            new_name='groupId',
        ),
        migrations.RenameField(
            model_name='callreport',
            old_name='status_name',
            new_name='groupName',
        ),
        migrations.RenameField(
            model_name='callreport',
            old_name='price_per_second',
            new_name='pricePerSecond',
        ),
        migrations.RenameField(
            model_name='callreport',
            old_name='bulk_id',
            new_name='scenarioId',
        ),
        migrations.RenameField(
            model_name='callreport',
            old_name='message_id',
            new_name='scenarioName',
        ),
        migrations.RenameField(
            model_name='callreport',
            old_name='spoken_input',
            new_name='spokenInput',
        ),
        migrations.RenameField(
            model_name='callreport',
            old_name='status_description',
            new_name='statusDescription',
        ),
        migrations.RenameField(
            model_name='callreport',
            old_name='status_id',
            new_name='statusId',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='answer_time',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='from_number',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='scenario_id',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='scenario_name',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='callreport',
            name='to_number',
        ),
        migrations.AddField(
            model_name='callreport',
            name='answerTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callreport',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callreport',
            name='fromNum',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='callreport',
            name='messageId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='callreport',
            name='sentAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callreport',
            name='startTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callreport',
            name='statusName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='callreport',
            name='to',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='callreport',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
