# Generated by Django 4.2.6 on 2024-07-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_remove_viewtimehistory_counts_viewtimehistory_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewtimehistory',
            name='access_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
