# Generated by Django 4.2.6 on 2024-07-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_remove_business_user_business_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='actions',
        ),
    ]
