# Generated by Django 4.2.6 on 2023-11-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_remove_campaign_actions_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONVERTED', 'Converted'), ('REJECTED', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
