# Generated by Django 4.2.6 on 2024-07-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_viewtimehistory_access_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewtimehistory',
            name='path',
        ),
    ]
