# Generated by Django 4.2.6 on 2023-11-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_campaign_converted_alter_campaign_leads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='type_of_campaign',
            new_name='type',
        ),
    ]
