# Generated by Django 4.2.6 on 2024-08-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_lead_contacted_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='recording_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
