# Generated by Django 4.2.6 on 2023-11-15 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_rename_type_of_campaign_campaign_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='type',
            new_name='type_of',
        ),
    ]
