# Generated by Django 4.2.6 on 2024-01-16 08:35

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_rename_type_campaign_type_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk_id', models.CharField(max_length=255)),
                ('message_id', models.CharField(max_length=255)),
                ('from_number', models.CharField(max_length=15)),
                ('to_number', models.CharField(max_length=15)),
                ('sent_at', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('answer_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('charged_duration', models.IntegerField()),
                ('file_duration', models.FloatField()),
                ('dtmf_codes', models.CharField(max_length=255)),
                ('scenario_id', models.CharField(max_length=255)),
                ('scenario_name', models.CharField(max_length=255)),
                ('collected_dtmfs', models.TextField()),
                ('spoken_input', models.TextField()),
                ('price_per_second', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('group_id', models.IntegerField()),
                ('group_name', models.CharField(max_length=255)),
                ('status_id', models.IntegerField()),
                ('status_name', models.CharField(max_length=255)),
                ('status_description', models.TextField()),
                ('error_group_id', models.IntegerField()),
                ('error_group_name', models.CharField(max_length=255)),
                ('error_id', models.IntegerField()),
                ('error_name', models.CharField(max_length=255)),
                ('error_description', models.TextField()),
                ('error_permanent', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='user_avatar/'),
        ),
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.EmailField(default='ikhidea4@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
