# Generated by Django 4.2.6 on 2024-08-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_lead_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='call_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='call_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
