# Generated by Django 4.2.6 on 2024-09-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_lead_call_duration_lead_call_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='content_option',
            field=models.CharField(choices=[('Audio', 'Audio'), ('Text', 'Text')], default='Autoleads Introduction', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='text_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='text_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='text_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='text_4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
