# Generated by Django 4.2.6 on 2024-10-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_campaign_content_option_campaign_text_1_and_more'),
        ('business', '0010_activitylog'),
    ]

    operations = [
    ]
