# Generated by Django 4.2.6 on 2024-10-22 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0011_merge_20241021_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewtimehistory',
            name='has_access',
            field=models.BooleanField(default=True),
        ),
    ]
