# Generated by Django 4.2.6 on 2024-10-22 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0011_merge_20241021_1101'),
    ]

    operations = [
        # Remove the issue field from the Support model
        migrations.RemoveField(
            model_name='support',
            name='issue',
        ),

        # Add new fields to the Support model
        migrations.AddField(
            model_name='support',
            name='subject',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]