# Generated by Django 4.2.6 on 2024-02-10 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_formdesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='callreport',
            name='campaign',
            field=models.ForeignKey(default='BH2O', on_delete=django.db.models.deletion.CASCADE, related_name='call_reports_campaign', to='business.campaign'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callreport',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_reports_lead', to='business.lead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Converted', 'Converted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
