# Generated by Django 4.2.6 on 2024-10-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_viewtimehistory_has_access_supportt'),
    ]

    operations = [
        # Remove the 'issue' field
        migrations.RemoveField(
            model_name='support',
            name='issue',
        ),

        # Add the 'subject' field
        migrations.AddField(
            model_name='support',
            name='subject',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),

        # Add the 'description' field
        migrations.AddField(
            model_name='support',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]