# Generated by Django 4.2.6 on 2024-02-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_callreport_campaign_alter_callreport_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contacted_status',
            field=models.CharField(blank=True, choices=[('Converted', 'Converted'), ('Rejected', 'Rejected')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Contacted', 'Contacted')], default='Pending', max_length=20),
        ),
    ]
