# Generated by Django 4.2.6 on 2024-10-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_viewtimehistory_has_access_supportt'),
    ]

    operations = [
    ]
