# Generated by Django 4.2.6 on 2024-05-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_remove_callreport_answer_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='call_scenario_id',
        ),
        migrations.AddField(
            model_name='lead',
            name='call_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
