# Generated by Django 4.2.6 on 2024-05-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_remove_campaign_call_scenario_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='extras',
            new_name='session_id',
        ),
    ]
