# Generated by Django 4.2.6 on 2024-05-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_remove_campaign_call_scenario_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='extras',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
