# Generated by Django 4.2.6 on 2024-06-27 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_remove_lead_call_session_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created']},
        ),
    ]
