# Generated by Django 4.2.6 on 2024-01-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callreport',
            name='collected_dtmfs',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callreport',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callreport',
            name='dtmf_codes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='callreport',
            name='price_per_second',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callreport',
            name='scenario_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callreport',
            name='scenario_name',
            field=models.CharField(default='Call 1', max_length=255),
            preserve_default=False,
        ),
    ]
