# Generated by Django 4.2.6 on 2024-01-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_callreport_delete_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callreport',
            name='mcc_mnc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
