# Generated by Django 4.2.6 on 2024-01-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_callreport_mcc_mnc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callreport',
            name='answer_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='callreport',
            name='end_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='callreport',
            name='sent_at',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='callreport',
            name='start_time',
            field=models.CharField(max_length=100),
        ),
    ]
