# Generated by Django 4.2.6 on 2024-01-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_callreport_answer_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callreport',
            name='call_back_data',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='callreport',
            name='from_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='callreport',
            name='mcc_mnc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='callreport',
            name='to_number',
            field=models.CharField(max_length=50),
        ),
    ]
