# Generated by Django 4.2.6 on 2024-01-31 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_alter_callreport_call_back_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callreport',
            name='lead',
            field=models.ForeignKey(default='CJNH', on_delete=django.db.models.deletion.CASCADE, related_name='call_reports', to='business.lead'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='audio_link_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='audio_link_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='audio_link_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='audio_link_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='call_scenario_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='contact_option',
            field=models.CharField(choices=[('CALL', 'Call'), ('SMS', 'Sms')], default='Call', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
