# Generated by Django 4.2.6 on 2024-06-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_alter_business_options_alter_campaign_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='check_it',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
