# Generated by Django 4.2.6 on 2024-06-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_lead_check_it'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='check_it',
        ),
    ]
